.DEFAULT_GOAL := build-run

run-dist:
	@./build/install/app/bin/app

run:
	gradle run

clean:
	gradle clean

build:
	gradle clean
	gradle build

install:
	gradle clean
	gradle installDist

.PHONY: build